import 'package:karmashala_devices/src/data/avd_system_images.dart';
import 'package:test/test.dart';

/// Where an AVD's system image is supposed to be.
///
/// `emulator -list-avds` lists directories, not bootable devices: two AVDs on
/// this machine listed perfectly on 2026-09-03 and then died with
/// `PANIC: Cannot find AVD system path` because their images had never been
/// downloaded. The image is named in a file, so it can be checked before three
/// minutes of boot are spent finding out.
void main() {
  group('iniValue', () {
    test('takes the value verbatim after the first =', () {
      // A Windows path is full of characters a cleverer parse would mangle.
      expect(
        iniValue(r'path=C:\Users\d\.android\avd\Pixel_9.avd', 'path'),
        r'C:\Users\d\.android\avd\Pixel_9.avd',
      );
    });

    test('ignores comments, blanks and other keys', () {
      const content = '''
# generated by Android Studio
avd.ini.encoding=UTF-8

path.rel=avd/Pixel_9.avd
target=android-34
''';
      expect(iniValue(content, 'path.rel'), 'avd/Pixel_9.avd');
      expect(iniValue(content, 'path'), isNull);
    });

    test('an empty value is not a value', () {
      expect(iniValue('path=\n', 'path'), isNull);
    });
  });

  group('avdDirectory', () {
    test('an absolute path wins', () {
      expect(
        avdDirectory(
          'path=/home/d/.android/avd/Pixel_9.avd\npath.rel=avd/Pixel_9.avd\n',
          avdHome: '/home/d/.android/avd',
          separator: '/',
        ),
        '/home/d/.android/avd/Pixel_9.avd',
      );
    });

    test('a relative path resolves against the .android directory', () {
      expect(
        avdDirectory(
          'path.rel=avd/Pixel_9.avd\n',
          avdHome: r'C:\Users\d\.android\avd',
          separator: r'\',
        ),
        r'C:\Users\d\.android\avd\Pixel_9.avd',
      );
    });

    test('an ini naming no folder yields nothing to check', () {
      expect(
        avdDirectory('target=android-34\n', avdHome: '/x/avd', separator: '/'),
        isNull,
      );
    });
  });

  group('systemImageDirectory', () {
    test('joins the SDK root to the sysdir the config names', () {
      expect(
        systemImageDirectory(
          'image.sysdir.1=system-images/android-34/google_apis/x86_64/\n',
          sdkRoot: r'C:\Users\d\AppData\Local\Android\Sdk',
          separator: r'\',
        ),
        r'C:\Users\d\AppData\Local\Android\Sdk\system-images\android-34'
        r'\google_apis\x86_64',
      );
    });

    test('the stored forward slashes and trailing slash are normalised', () {
      expect(
        systemImageDirectory(
          'image.sysdir.1=system-images/android-33/default/arm64-v8a/\n',
          sdkRoot: '/home/d/Android/Sdk',
          separator: '/',
        ),
        '/home/d/Android/Sdk/system-images/android-33/default/arm64-v8a',
      );
    });

    test('a config naming no image yields nothing to check', () {
      expect(
        systemImageDirectory(
          'hw.lcd.density=440\n',
          sdkRoot: '/sdk',
          separator: '/',
        ),
        isNull,
      );
    });
  });

  group('AvdImageStatus', () {
    test('an unreadable AVD is unknown, not broken', () {
      const status = AvdImageStatus.unknown('Pixel_9', 'its ini was gone');
      expect(status.checked, isFalse);
      expect(status.missingImage, isFalse);
      expect(status.problem, 'its ini was gone');
    });

    test('a missing image is a checked finding with a path', () {
      const status = AvdImageStatus.missingSystemImage('Pixel_9', '/sdk/x');
      expect(status.checked, isTrue);
      expect(status.missingImage, isTrue);
      expect(status.imagePath, '/sdk/x');
    });
  });
}
