import 'dart:convert';
import 'dart:io';

import 'package:agent_cli/src/agents/domain/agent_ids.dart';
import 'package:agent_cli/src/cli_detection/data/cli_transcript_reader.dart';
import 'package:test/test.dart';

import '../support/temp_directory.dart';

/// What the person ran themselves in a Claude Code terminal: a slash command
/// and `!` shell mode, recorded as tagged user turns (older CLIs) or
/// `system/local_command` records (newer). Shapes are the recorded ones; the
/// text is made up.
void main() {
  late Directory dir;

  setUp(() => dir = Directory.systemTemp.createTempSync('local_command_test'));
  tearDown(() => removeTempDirectory(dir));

  Future<List<TranscriptMessage>> read(List<Map<String, Object?>> records) {
    final file = File('${dir.path}/t.jsonl')
      ..writeAsStringSync(records.map(jsonEncode).join('\n'));
    return readCliTranscript(file.path, AgentIds.claudeCode);
  }

  Map<String, Object?> user(String content, {bool meta = false}) => {
    'type': 'user',
    if (meta) 'isMeta': true,
    'message': {'role': 'user', 'content': content},
  };

  Map<String, Object?> local(String content) => {
    'type': 'system',
    'subtype': 'local_command',
    'content': content,
    'level': 'info',
    'isMeta': false,
  };

  test('a slash command is one row with its output, no tags', () async {
    final messages = await read([
      user(
        '<local-command-caveat>Caveat: generated by a local command.'
        '</local-command-caveat>',
        meta: true,
      ),
      user(
        '<command-name>/model</command-name>\n'
        '            <command-message>model</command-message>\n'
        '            <command-args>opus</command-args>',
      ),
      user(
        '<local-command-stdout>Set model to \u001b[1mopus\u001b[22m'
        '</local-command-stdout>',
      ),
    ]);

    expect(messages, hasLength(1));
    final row = messages.single;
    expect(row.role, kTranscriptCommandRole);
    expect(row.tool!.name, '/model');
    expect(row.tool!.subject, 'opus');
    expect(row.tool!.output, 'Set model to opus');
    expect(row.text, isNot(contains('<')));
  });

  test('the newer system records read the same way', () async {
    final messages = await read([
      local(
        '<command-name>/context</command-name>\n'
        '<command-message>context</command-message>\n'
        '<command-args></command-args>',
      ),
      {
        ...local(
          '<local-command-stdout>12k of 200k used</local-command-stdout>',
        ),
        'commandRun': true,
      },
    ]);

    expect(messages.single.tool!.name, '/context');
    expect(messages.single.tool!.subject, isNull);
    expect(messages.single.tool!.output, '12k of 200k used');
  });

  test('a ! command is a shell row with what it printed', () async {
    final messages = await read([
      user('<bash-input>echo hi</bash-input>'),
      user('<bash-stdout>hi</bash-stdout><bash-stderr>warn</bash-stderr>'),
      user('thanks'),
    ]);

    expect(messages.map((m) => m.role), [kTranscriptCommandRole, 'user']);
    final shell = messages.first.tool!;
    expect(shell.name, 'Shell');
    expect(shell.subject, 'echo hi');
    expect(shell.output, 'hi\nwarn');
  });
}
