import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:sqlite3/sqlite3.dart';

import 'migrations.dart';

/// The application's SQLite database.
///
/// Persistence uses the `sqlite3` package directly with hand-written SQL — there
/// is **no code generation** anywhere in the project. The schema is created and
/// migrated imperatively via the ordered steps in [schemaMigrations], keyed off
/// SQLite's `PRAGMA user_version`.
///
/// This type owns the connection and exposes small, typed helpers ([query],
/// [execute], [transaction], [lastInsertRowId]). Feature data-access objects
/// (DAOs) depend on those helpers and hold their own SQL, so the `sqlite3`
/// dependency stays confined to this file and never leaks into features.
class AppDatabase {
  AppDatabase(this._db) {
    _migrate();
  }

  final Database _db;

  /// Current schema version. Equal to the highest key in [schemaMigrations].
  int get schemaVersion => schemaMigrations.length;

  /// Opens the database backed by a file in the per-user application-support
  /// directory (outside the project tree).
  static Future<AppDatabase> open() async {
    final dir = await getApplicationSupportDirectory();
    final file = p.join(dir.path, 'chitragupta.sqlite');
    return AppDatabase(sqlite3.open(file));
  }

  /// Opens an ephemeral in-memory database, for tests.
  factory AppDatabase.memory() => AppDatabase(sqlite3.openInMemory());

  // --- Schema management -----------------------------------------------------

  void _migrate() {
    _db.execute('PRAGMA foreign_keys = ON;');
    var current = _userVersion;
    while (current < schemaVersion) {
      final next = current + 1;
      final step = schemaMigrations[next];
      if (step == null) {
        throw StateError('Missing migration step for schema version $next.');
      }
      _db.execute('BEGIN;');
      try {
        step(_db);
        _db.execute('PRAGMA user_version = $next;');
        _db.execute('COMMIT;');
      } catch (_) {
        _db.execute('ROLLBACK;');
        rethrow;
      }
      current = next;
    }
  }

  int get _userVersion =>
      _db.select('PRAGMA user_version;').first.values.first! as int;

  // --- Query helpers ---------------------------------------------------------

  /// Runs a SELECT and returns rows as plain column-name → value maps.
  ///
  /// Returning maps (rather than the `sqlite3` `ResultSet`) keeps the `sqlite3`
  /// types out of feature code.
  List<Map<String, Object?>> query(
    String sql, [
    List<Object?> params = const [],
  ]) {
    final result = _db.select(sql, params);
    final columns = result.columnNames;
    return [
      for (final row in result)
        {for (final column in columns) column: row[column]},
    ];
  }

  /// Runs a non-SELECT statement (INSERT/UPDATE/DELETE/DDL).
  void execute(String sql, [List<Object?> params = const []]) {
    _db.execute(sql, params);
  }

  /// Rowid generated by the most recent INSERT on this connection.
  int get lastInsertRowId => _db.lastInsertRowId;

  /// Runs [action] inside a transaction, rolling back if it throws.
  T transaction<T>(T Function() action) {
    _db.execute('BEGIN;');
    try {
      final result = action();
      _db.execute('COMMIT;');
      return result;
    } catch (_) {
      _db.execute('ROLLBACK;');
      rethrow;
    }
  }

  // --- App metadata (key/value store) ---------------------------------------

  /// Reads a metadata value by [key], or `null` if absent.
  String? readMetadata(String key) {
    final rows = query('SELECT value FROM app_metadata WHERE key = ?;', [key]);
    if (rows.isEmpty) return null;
    return rows.first['value'] as String;
  }

  /// Inserts or updates a metadata [key] with [value], stamping `updated_at`.
  void writeMetadata(String key, String value) {
    execute(
      'INSERT INTO app_metadata (key, value, updated_at) VALUES (?, ?, ?) '
      'ON CONFLICT(key) DO UPDATE SET '
      'value = excluded.value, updated_at = excluded.updated_at;',
      [key, value, DateTime.now().toUtc().toIso8601String()],
    );
  }

  /// Releases the underlying database handle.
  void close() => _db.close();
}
