import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:sqlite3/sqlite3.dart';

import 'migrations.dart';

/// The application's SQLite database.
///
/// Persistence uses the `sqlite3` package directly with hand-written SQL — there
/// is **no code generation** anywhere in the project. The schema is created and
/// migrated imperatively via the ordered steps in [schemaMigrations], keyed off
/// SQLite's `PRAGMA user_version`.
///
/// This type owns the connection and exposes small, typed helpers ([query],
/// [execute], [transaction], [lastInsertRowId]). Feature data-access objects
/// (DAOs) depend on those helpers and hold their own SQL, so the `sqlite3`
/// dependency stays confined to this file and never leaks into features.
class AppDatabase {
  AppDatabase(this._db) {
    _migrate();
  }

  final Database _db;

  /// Current schema version: the highest key in [schemaMigrations].
  ///
  /// Read from the keys rather than from `schemaMigrations.length`, which is
  /// the same number **only while the keys are dense**. They are not always:
  /// two feature branches in flight both claim the next version, and whichever
  /// merges second has to renumber, so a branch legitimately holds a migration
  /// numbered above a gap until the merge closes it. `length` answered that
  /// situation with a lower number than the migrations it was describing, which
  /// would stamp a freshly migrated database with a version *behind* its own
  /// schema — the one error in a migration runner that no later run can detect,
  /// because it is indistinguishable from a database that legitimately stopped
  /// there.
  int get schemaVersion =>
      schemaMigrations.keys.fold(0, (a, b) => a > b ? a : b);

  /// Opens the database backed by a file in the per-user application-support
  /// directory (outside the project tree).
  static Future<AppDatabase> open() async {
    final dir = await getApplicationSupportDirectory();
    final file = p.join(dir.path, 'chitragupta.sqlite');
    return AppDatabase(sqlite3.open(file));
  }

  /// Opens an ephemeral in-memory database, for tests.
  factory AppDatabase.memory() => AppDatabase(sqlite3.openInMemory());

  // --- Schema management -----------------------------------------------------

  /// Applies every step whose version is greater than the stored
  /// `PRAGMA user_version`, in ascending order, each in its own transaction.
  ///
  /// Driven by the map's own sorted keys rather than by counting up from the
  /// stored version, which is the same thing whenever the keys are dense and
  /// **a hard failure when they are not**: the old loop asked for version
  /// `current + 1` and threw `Missing migration step` if a branch had renumbered
  /// around a gap, refusing to open a database it could have migrated
  /// perfectly well.
  ///
  /// This is what the doc comment on [schemaMigrations] has always described.
  /// The counting loop was a stricter approximation of it that happened to
  /// agree until two loops landed migrations at once.
  void _migrate() {
    _db.execute('PRAGMA foreign_keys = ON;');
    final current = _userVersion;
    final pending = schemaMigrations.keys.where((v) => v > current).toList()
      ..sort();
    for (final version in pending) {
      _db.execute('BEGIN;');
      try {
        schemaMigrations[version]!(_db);
        _db.execute('PRAGMA user_version = $version;');
        _db.execute('COMMIT;');
      } catch (_) {
        _db.execute('ROLLBACK;');
        rethrow;
      }
    }
  }

  int get _userVersion =>
      _db.select('PRAGMA user_version;').first.values.first! as int;

  // --- Query helpers ---------------------------------------------------------

  /// Runs a SELECT and returns rows as plain column-name → value maps.
  ///
  /// Returning maps (rather than the `sqlite3` `ResultSet`) keeps the `sqlite3`
  /// types out of feature code.
  List<Map<String, Object?>> query(
    String sql, [
    List<Object?> params = const [],
  ]) {
    final result = _db.select(sql, params);
    final columns = result.columnNames;
    return [
      for (final row in result)
        {for (final column in columns) column: row[column]},
    ];
  }

  /// Runs a non-SELECT statement (INSERT/UPDATE/DELETE/DDL).
  void execute(String sql, [List<Object?> params = const []]) {
    _db.execute(sql, params);
  }

  /// Rowid generated by the most recent INSERT on this connection.
  int get lastInsertRowId => _db.lastInsertRowId;

  /// Runs [action] inside a transaction, rolling back if it throws.
  T transaction<T>(T Function() action) {
    _db.execute('BEGIN;');
    try {
      final result = action();
      _db.execute('COMMIT;');
      return result;
    } catch (_) {
      _db.execute('ROLLBACK;');
      rethrow;
    }
  }

  // --- App metadata (key/value store) ---------------------------------------

  /// Reads a metadata value by [key], or `null` if absent.
  String? readMetadata(String key) {
    final rows = query('SELECT value FROM app_metadata WHERE key = ?;', [key]);
    if (rows.isEmpty) return null;
    return rows.first['value'] as String;
  }

  /// Inserts or updates a metadata [key] with [value], stamping `updated_at`.
  void writeMetadata(String key, String value) {
    execute(
      'INSERT INTO app_metadata (key, value, updated_at) VALUES (?, ?, ?) '
      'ON CONFLICT(key) DO UPDATE SET '
      'value = excluded.value, updated_at = excluded.updated_at;',
      [key, value, DateTime.now().toUtc().toIso8601String()],
    );
  }

  /// Releases the underlying database handle.
  void close() => _db.close();
}
