import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:sqlite3/sqlite3.dart';

import 'migrations.dart';

/// The app's SQLite database: hand-written SQL, no code generation. Owns the
/// connection and the typed helpers, so `sqlite3` never leaks into features.
class AppDatabase {
  AppDatabase(this._db) {
    _configure();
    _migrate();
  }

  final Database _db;

  /// Current schema version: the highest key in [schemaMigrations], not
  /// `.length` — a branch may legitimately hold a migration numbered above a gap.
  int get schemaVersion =>
      schemaMigrations.keys.fold(0, (a, b) => a > b ? a : b);

  /// Opens the database backed by a file in [directory]. The caller supplies it
  /// so `path_provider`, and with it Flutter, stays out of this file.
  static AppDatabase open(Directory directory) =>
      AppDatabase(sqlite3.open(p.join(directory.path, 'karmashala.sqlite')));

  /// Opens an ephemeral in-memory database, for tests.
  factory AppDatabase.memory() => AppDatabase(sqlite3.openInMemory());


  /// Connection settings, applied once before any other statement. WAL, and
  /// `synchronous = NORMAL` only once WAL is in effect — see docs/SETTLED.md.
  void _configure() {
    _db.execute('PRAGMA foreign_keys = ON;');
    // A second writer (a debug build beside the installed app) waits instead
    // of throwing SQLITE_BUSY out of whatever menu handler it lands in.
    _db.execute('PRAGMA busy_timeout = 5000;');
    try {
      _db.execute('PRAGMA journal_mode = WAL;');
    } on SqliteException {
      // Locked by another connection, or a filesystem with no shared memory.
      // The rollback journal is slower, not wrong.
      return;
    }
    if (journalMode != 'wal') return;
    _db.execute('PRAGMA synchronous = NORMAL;');
  }

  /// The journal mode this connection actually got, lower-cased. Read rather
  /// than assumed: [_configure] asks for WAL and SQLite is entitled to say no.
  String get journalMode =>
      (_db.select('PRAGMA journal_mode;').first.values.first! as String)
          .toLowerCase();

  /// Applies every step above the stored `PRAGMA user_version` in ascending
  /// order, each in its own transaction. Driven by the keys, so a gap is fine.
  void _migrate() {
    final current = _userVersion;
    final pending = schemaMigrations.keys.where((v) => v > current).toList()
      ..sort();
    for (final version in pending) {
      _db.execute('BEGIN;');
      try {
        schemaMigrations[version]!(_db);
        _db.execute('PRAGMA user_version = $version;');
        _db.execute('COMMIT;');
      } catch (_) {
        _db.execute('ROLLBACK;');
        rethrow;
      }
    }
  }

  int get _userVersion =>
      _db.select('PRAGMA user_version;').first.values.first! as int;


  /// Runs a SELECT and returns rows as plain column-name → value maps, which
  /// keeps the `sqlite3` types out of feature code.
  List<Map<String, Object?>> query(
    String sql, [
    List<Object?> params = const [],
  ]) {
    final result = _db.select(sql, params);
    final columns = result.columnNames;
    return [
      for (final row in result)
        {for (final column in columns) column: row[column]},
    ];
  }

  /// Runs a non-SELECT statement (INSERT/UPDATE/DELETE/DDL).
  void execute(String sql, [List<Object?> params = const []]) {
    _db.execute(sql, params);
  }

  /// Rowid generated by the most recent INSERT on this connection.
  int get lastInsertRowId => _db.lastInsertRowId;

  /// Runs [action] inside a transaction, rolling back if it throws.
  T transaction<T>(T Function() action) {
    _db.execute('BEGIN;');
    try {
      final result = action();
      _db.execute('COMMIT;');
      return result;
    } catch (_) {
      _db.execute('ROLLBACK;');
      rethrow;
    }
  }


  /// Reads a metadata value by [key], or `null` if absent.
  String? readMetadata(String key) {
    final rows = query('SELECT value FROM app_metadata WHERE key = ?;', [key]);
    if (rows.isEmpty) return null;
    return rows.first['value'] as String;
  }

  /// Inserts or updates a metadata [key] with [value], stamping `updated_at`.
  void writeMetadata(String key, String value) {
    execute(
      'INSERT INTO app_metadata (key, value, updated_at) VALUES (?, ?, ?) '
      'ON CONFLICT(key) DO UPDATE SET '
      'value = excluded.value, updated_at = excluded.updated_at;',
      [key, value, DateTime.now().toUtc().toIso8601String()],
    );
  }

  /// Releases the underlying database handle.
  void close() => _db.close();
}
